name: CI

on:
  - push
  - pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      API_PORT: 3000
      MONGO_USER: admin
      MONGO_PASSWORD: admin123
      ENVIRONMENT: local
      MONGO_HOST: localhost:27017
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      MAILTRAP_TOKEN: ${{ secrets.MAILTRAP_TOKEN }}
      INBOXID: ${{ secrets.INBOXID }}
      IS_SANDBOX: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create .env file
        run: |
          cat > .env << EOF
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          API_PORT=3000
          MONGO_USER=admin
          MONGO_PASSWORD=admin123
          ENVIRONMENT=local
          MONGO_HOST=localhost:27017
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          MAILTRAP_TOKEN=${{ secrets.MAILTRAP_TOKEN }}
          INBOXID=${{ secrets.INBOXID }}
          IS_SANDBOX=true
          EOF

      - name: Run tests
        run: pnpm test

      - name: Run linter
        run: pnpm lint

      - name: Build project
        run: pnpm build
